spring.application.name=booking-service
server.port=8082

eureka.client.service-url.defaultZone = http://localhost:9000/eureka/

spring.datasource.url=${DB_URL}
spring.jpa.properties.hibernate.default_schema=${DB_SCHEMA}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

spring.rabbitmq.host=${RABBIT_MQ_HOST}
spring.rabbitmq.port=${RABBIT_MQ_PORT}
spring.rabbitmq.username=${RABBIT_MQ_USERNAME}
spring.rabbitmq.password=${RABBIT_MQ_PASSWORD}
spring.rabbitmq.virtual-host=${RABBIT_MQ_VHOST}

logging.level.org.springframework.amqp=DEBUG
logging.level.org.springframework.rabbit=DEBUG
logging.level.org.springframework.amqp.rabbit.connection=DEBUG
logging.level.com.rabbitmq=DEBUG
logging.level.org.springframework.boot.autoconfigure.amqp=DEBUG