spring.application.name=payment-service
spring.config.import=optional:file:.env[.properties]
server.port=8085
spring.datasource.url=${DB_URL}
spring.jpa.properties.hibernate.default_schema=${DB_SCHEMA}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

payment.gateway.mock-enabled=true

razorpay.key-id=${RAZORPAY_KEY_ID}
razorpay.key-secret=${RAZORPAY_KEY_SECRET}
razorpay.webhook-secret=${RAZORPAY_WEBHOOK_SECRET}

# Rabbit MQ configuration
spring.rabbitmq.host=${RABBIT_MQ_HOST}
spring.rabbitmq.port=${RABBIT_MQ_PORT}
spring.rabbitmq.username=${RABBIT_MQ_USERNAME}
spring.rabbitmq.password=${RABBIT_MQ_PASSWORD}
spring.rabbitmq.virtual-host=${RABBIT_MQ_VHOST}

logging.level.org.springframework.amqp=DEBUG
logging.level.org.springframework.rabbit=DEBUG
logging.level.org.springframework.amqp.rabbit.connection=DEBUG
logging.level.com.rabbitmq=DEBUG
logging.level.org.springframework.boot.autoconfigure.amqp=DEBUG
eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://localhost:9000/eureka}