spring.application.name=theatre-service
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.jpa.properties.hibernate.default_schema=${DB_SCHEMA}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Ensure the driver is specified
spring.datasource.driver-class-name=org.postgresql.Driver

eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://localhost:9000/eureka}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
