spring.application.name=movie-service
server.port=8081
eureka.client.service-url.defaultZone = http://localhost:9000/eureka/

spring.datasource.url=jdbc:postgresql://ep-twilight-butterfly-adp9s7jb-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require&currentSchema=movie_service
spring.jpa.properties.hibernate.default_schema=movie_service
spring.datasource.username=neondb_owner
spring.datasource.password=npg_7LVXU1MTOiua
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
# Ensure the driver is specified
spring.datasource.driver-class-name=org.postgresql.Driver